### ISSUE TITLE
Parsing error: Unexpected keyword or identifier

### ISSUE THREAD

**Issue by eng-dibo** [ota-meshi/eslint-plugin-css#34]
**Information:**
- ESLint version: latest
- `eslint-plugin-css` version: latest

I'm trying to lint a simple .css file 
```
a{
 color: red;
}
```
but I got the error `Parsing error: Unexpected keyword or identifier`

I use `@typescript-eslint/parser`

**Comment by ota-meshi** [comment]
This plugin does not target css files. I recommend that you use Stylelint instead.

**Comment by jefhar** [comment]
@ota-meshi If this package is called `eslint-plugin-css` and it doesn't target css files, the package is named incorrectly.
