### ISSUE TITLE
Indentation rule for Single File Components

### ISSUE THREAD

**Issue by Erveon** [ota-meshi/eslint-plugin-css#39]
**Description**

It would be nice to be able to set a rule for indentation in Single File Components.  
The most prominent parts would be whether to use tabs or spaces, and the width of each indent.
This would go under the `Stylistic Issues` category and would be auto-fixable.

@ota-meshi if you are OK with this rule being introduced, I wouldn't mind trying to create it.
I haven't made an ESLint rule before but I figure it might be a fun challenge.

If I'm overlooking different ways to introduce this rule to CSS in Single File Components using ESLint without adding a new rule here, feel free to point it out.

**Comment by ota-meshi** [comment]
Thanks for posting issue. But I don't know what your request is.

Do you want to indent with Vue's SFC? If so, I think eslint-plugin-vue's `vue/html-indent` rule will do that.
https://eslint.vuejs.org/rules/html-indent.html

https://ota-meshi.github.io/eslint-plugin-vue-demo/#eJxNjMkKwyAURX9FXhfZRIQsxfZL3AR9UotDcSIl+O+1FUpX5w5wTlBRI3AQBf3T7QVvMhAitG0fEsJzeTm8Spj1nFDRxcTJcjHGLHPqExKmgA3DSIL9eWGFVB1m4Ce0iuxevKM2aAwF+LZ+NxW9H51qm1AV2/D3PPJBa8ZM256GYuv9DcVwPMw=

Or are you talking about style tags?
If so, I think you can use [stylelint](https://stylelint.io/).

**Comment by Erveon** [comment]
> Thanks for posting issue. But I don't know what your request is.
> 
> Do you want to indent with Vue's SFC? If so, I think eslint-plugin-vue's `vue/html-indent` rule will do that. https://eslint.vuejs.org/rules/html-indent.html
> 
> https://ota-meshi.github.io/eslint-plugin-vue-demo/#eJxNjMkKwyAURX9FXhfZRIQsxfZL3AR9UotDcSIl+O+1FUpX5w5wTlBRI3AQBf3T7QVvMhAitG0fEsJzeTm8Spj1nFDRxcTJcjHGLHPqExKmgA3DSIL9eWGFVB1m4Ce0iuxevKM2aAwF+LZ+NxW9H51qm1AV2/D3PPJBa8ZM256GYuv9DcVwPMw=
> 
> Or are you talking about style tags? If so, I think you can use [stylelint](https://stylelint.io/).

I did mean style tags. After looking into a bit more it does look like stylelint supports this through an ESLint extension, thank you!
