### ISSUE TITLE
The table element in update-named-colors.ts should eliminate null.

### ISSUE THREAD

**Issue by nojiritakeshi** [ota-meshi/eslint-plugin-css#92]
Sorry for my poor English.

The process is progressing with the possibility that the table element being retrieved in the collectValues method of update-named-colors.ts is null.
For example, I think it would be better to guarantee that it is an HTMLTableElement with the following code.
```js:./lib/dom_util.ts
export function isHTMLTableElement(
  table: Element | null
): table is HTMLTableElement {
  return table != null && table.tagName === "TABLE";
}
```
My apologies if this is a misguided point of view.
If the points I make are good ones, may I make a pull request?

**Comment by ota-meshi** [comment]
Thank you for posting this issue!


I think it makes sense to add that check. Feel free to submit pull requests.

> Sorry for my poor English.

Don't worry I use poor English.
