### ISSUE TITLE
Parsing error: Unexpected character '@'

### ISSUE THREAD

**Issue by tex0l** [ota-meshi/eslint-plugin-css#95]
**Information:**
- ESLint version: v8.42.0
- `eslint-plugin-css` version: 0.8.0

**Description**
A file containing: `@import url('font-awesome/css/font-awesome.css');` fails at linting with `Parsing error: Unexpected character '@'`

**Expected behavior**
It should work.

**Comment by ota-meshi** [comment]
This plugin is not a plugin that checks CSS files.

**Comment by vanowm** [comment]
I'm confused. What does this plugin do then? If it's not about css, then perhaps it should be renamed to something more specific...
